-- Seed généré depuis l'ancien contenu en dur (lib/content.js, lib/services.js, lib/site.js)

DELETE FROM site_settings;
INSERT INTO site_settings (key, value) VALUES ('name', 'Akeva Care Sérénité 24');
INSERT INTO site_settings (key, value) VALUES ('shortName', 'Akeva Care');
INSERT INTO site_settings (key, value) VALUES ('tagline', 'Prendre soin de vos proches, même lorsque vous ne pouvez pas être là.');
INSERT INTO site_settings (key, value) VALUES ('promise', 'Un accompagnement professionnel et humain à domicile et à l''hôpital.');
INSERT INTO site_settings (key, value) VALUES ('description', 'Akeva Care Sérénité 24 accompagne les personnes âgées, les personnes dépendantes et les patients à domicile ou à l''hôpital à Yaoundé et Douala. Présence professionnelle, humaine et personnalisée.');
INSERT INTO site_settings (key, value) VALUES ('url', 'https://akevacare.cm');
INSERT INTO site_settings (key, value) VALUES ('email', 'contact@akevacare.cm');
INSERT INTO site_settings (key, value) VALUES ('phoneDisplay', '+237 6 99 00 24 24');
INSERT INTO site_settings (key, value) VALUES ('phoneTel', '+237699002424');
INSERT INTO site_settings (key, value) VALUES ('whatsapp', '237699002424');
INSERT INTO site_settings (key, value) VALUES ('cities', '["Yaoundé","Douala"]');
INSERT INTO site_settings (key, value) VALUES ('hours', '24h/24 · 7j/7');

DELETE FROM why_points;
INSERT INTO why_points (order_index, title, text) VALUES (0, 'Personnel sélectionné et encadré', 'Chaque intervenant est choisi, briefé et suivi. Vous n''accueillez pas un inconnu « trouvé au hasard ».');
INSERT INTO why_points (order_index, title, text) VALUES (1, 'Accompagnement personnalisé', 'Horaires, habitudes, langue, rythme, points de vigilance : rien n''est standardisé à l''excès.');
INSERT INTO why_points (order_index, title, text) VALUES (2, 'Intervention à domicile et à l''hôpital', 'Un seul interlocuteur, que votre proche soit chez lui ou hospitalisé.');
INSERT INTO why_points (order_index, title, text) VALUES (3, 'Organisation professionnelle', 'Évaluation, proposition, relais, suivi : une structure, pas une débrouille.');
INSERT INTO why_points (order_index, title, text) VALUES (4, 'Suivi de la famille', 'Vous savez ce qui se passe. Surtout si vous vivez à l''étranger.');
INSERT INTO why_points (order_index, title, text) VALUES (5, 'Disponibilité selon les besoins', 'Quelques heures, une nuit, une semaine, une présence 24h/24.');
INSERT INTO why_points (order_index, title, text) VALUES (6, 'Présence à Yaoundé et Douala', 'Deux villes, une même exigence de sérieux et d''humanité.');

DELETE FROM steps;
INSERT INTO steps (order_index, step_no, title, text) VALUES (0, '01', 'Contactez-nous', 'Téléphone, WhatsApp ou formulaire. Un premier échange suffit pour commencer.');
INSERT INTO steps (order_index, step_no, title, text) VALUES (1, '02', 'Expliquez votre situation', 'Un conseiller recueille les informations nécessaires, avec calme et confidentialité.');
INSERT INTO steps (order_index, step_no, title, text) VALUES (2, '03', 'Nous évaluons vos besoins', 'Lieu, horaires, situation du proche et type d''accompagnement.');
INSERT INTO steps (order_index, step_no, title, text) VALUES (3, '04', 'Nous proposons une solution', 'Formule et organisation adaptées — claires, sans surprise inutile.');
INSERT INTO steps (order_index, step_no, title, text) VALUES (4, '05', 'L''accompagnement commence', 'Akeva Care organise l''intervention et assure le suivi auprès de la famille.');

DELETE FROM faqs;
INSERT INTO faqs (order_index, question, answer) VALUES (0, 'Akeva Care est-il un service médical ?', 'Non. Akeva Care est un service d''accompagnement à la personne : présence, aide quotidienne, surveillance dans les limites professionnelles, lien avec la famille. Nous ne remplaçons pas un médecin, un infirmier ou un établissement de santé. Nous travaillons en complément du suivi médical existant.');
INSERT INTO faqs (order_index, question, answer) VALUES (1, 'Intervenez-vous à domicile et à l''hôpital ?', 'Oui. Nous organisons des présences à domicile et des accompagnements hospitaliers à Yaoundé et à Douala, selon les besoins et les règles de l''établissement.');
INSERT INTO faqs (order_index, question, answer) VALUES (2, 'Puis-je organiser un accompagnement depuis l''étranger ?', 'Oui, c''est une de nos missions centrales. La diaspora peut tout organiser à distance : évaluation, mise en place, suivi et comptes-rendus. WhatsApp et le téléphone suffisent pour démarrer.');
INSERT INTO faqs (order_index, question, answer) VALUES (3, 'En combien de temps pouvez-vous intervenir ?', 'Cela dépend de la ville, du type de présence et de la disponibilité. Certaines demandes se mettent en place rapidement, d''autres demandent une organisation plus fine. Expliquez-nous la situation : nous vous dirons clairement ce qui est possible.');
INSERT INTO faqs (order_index, question, answer) VALUES (4, 'Quels sont vos tarifs ?', 'Chaque situation est différente (jour, nuit, 24h, hôpital, durée, intensité). Nous établissons un devis après avoir compris le besoin. Pas de grille figée envoyée sans échange — pour éviter les mauvaises surprises.');
INSERT INTO faqs (order_index, question, answer) VALUES (5, 'Comment sont choisis les intervenants ?', 'Le personnel est sélectionné, briefé sur la situation de votre proche et encadré. Nous attachons autant d''importance au savoir-être qu''à la fiabilité.');
INSERT INTO faqs (order_index, question, answer) VALUES (6, 'Que se passe-t-il si l''intervenant ne convient pas ?', 'Dites-le-nous. L''accompagnement est un métier de relation : si le feeling ou le niveau de présence n''est pas le bon, nous réorganisons.');
INSERT INTO faqs (order_index, question, answer) VALUES (7, 'Intervenez-vous la nuit et le week-end ?', 'Oui. Garde de nuit, week-end, jours fériés et accompagnement 24h/24 font partie de notre offre, selon organisation.');
INSERT INTO faqs (order_index, question, answer) VALUES (8, 'Proposez-vous de la location de matériel médical ?', 'Oui, selon disponibilités : fauteuil, déambulateur, lit, aides techniques courantes. Demandez-nous ce dont vous avez besoin.');
INSERT INTO faqs (order_index, question, answer) VALUES (9, 'Accompagnez-vous les personnes concernées par des troubles psychiques ?', 'Oui, sous forme d''accompagnement quotidien, toujours en complément du suivi des professionnels de santé. Nous n''établissons aucun diagnostic et n''intervenons pas à la place d''un service de psychiatrie.');

DELETE FROM formulas;
INSERT INTO formulas (order_index, name, tag, text, points, featured) VALUES (0, 'Présence jour', 'Le quotidien', 'Quelques heures ou la journée complète à domicile. Idéal pour les repas, l''aide quotidienne et la compagnie.', '["Créneaux flexibles","Aide aux actes du quotidien","Point à la famille"]', 0);
INSERT INTO formulas (order_index, name, tag, text, points, featured) VALUES (1, 'Présence nuit', 'La vigilance', 'Une veille organisée à domicile ou à l''hôpital, lorsque la nuit est le moment le plus fragile.', '["Garde de nuit","Surveillance selon nos limites","Alerte familiale si besoin"]', 0);
INSERT INTO formulas (order_index, name, tag, text, points, featured) VALUES (2, 'Présence 24h/24', 'La continuité', 'Une organisation en relais pour les situations de grande dépendance ou de besoin permanent.', '["Relais organisés","Plan personnalisé","Suivi rapproché de la famille"]', 1);
INSERT INTO formulas (order_index, name, tag, text, points, featured) VALUES (3, 'Hospitalier', 'L''hôpital', 'Une présence au chevet, en journée ou la nuit, lorsque la famille ne peut pas rester.', '["Garde hospitalière","Respect de l''établissement","Lien avec la famille"]', 0);
INSERT INTO formulas (order_index, name, tag, text, points, featured) VALUES (4, 'Diaspora', 'Depuis l''étranger', 'Tout organiser à distance : évaluation, mise en place, comptes-rendus, interlocuteur unique.', '["Pilotage à distance","Comptes-rendus réguliers","Yaoundé et Douala"]', 0);

DELETE FROM articles;
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('choisir-une-garde-malade', 0, 'Comment choisir une garde malade à Yaoundé ou Douala', 'Présence, limites professionnelles, suivi de la famille : les questions à poser avant de confier un proche.', '12 août 2026', '/images/svc-hopital.jpg', 'Familles', NULL, 'Confier un parent à une garde malade n''est jamais un geste anodin. Au Cameroun, l''offre est inégale : entre la voisine dévouée, l''intermédiaire informel et une structure organisée, les écarts de sérieux sont immenses.

La première question n''est pas « combien ça coûte ? » mais « que fera concrètement la personne, et que ne fera-t-elle pas ? ». Une garde malade n''est pas un médecin. Elle n''est pas non plus une simple présence assise dans un coin. Elle aide, surveille, rassure, transmet.

Demandez toujours : qui encadre l''intervenant ? Que se passe-t-il la nuit ? Comment êtes-vous informés si vous vivez à l''étranger ? Qui remplace la personne si elle est absente ?

Chez Akeva Care, ces réponses font partie du service. Pas d''à-peu-près : une évaluation, une proposition, un suivi.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('organiser-accompagnement-depuis-etranger', 1, 'Organiser l''accompagnement d''un parent depuis l''étranger', 'France, Belgique, Canada, États-Unis : comment rester proche quand on vit loin de Yaoundé ou Douala.', '4 août 2026', '/images/hero-hands.jpg', 'Diaspora', NULL, 'La culpabilité de la diaspora a une forme précise : le téléphone qui sonne trop tard, le voisin qui « passe quand il peut », la tante épuisée, l''hôpital où personne ne reste la nuit.

Organiser un accompagnement à distance est possible, à condition d''avoir un interlocuteur unique, des comptes-rendus réguliers et une structure qui ne disparaît pas après le premier versement.

Commencez par décrire la situation sans minimiser : autonomie, logement, ville, horaires, hospitalisation en cours ou non. WhatsApp suffit pour ce premier échange.

Ensuite seulement vient l''organisation : qui intervient, quand, comment vous êtes tenus au courant, comment l''on ajuste si l''état de votre proche évolue.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('retour-domicile-apres-hopital', 2, 'Préparer le retour à domicile après une hospitalisation', 'Les premiers jours chez soi sont souvent les plus délicats. Voici comment les sécuriser.', '22 juillet 2026', '/images/svc-jour.jpg', 'Après l''hôpital', NULL, 'Sortir de l''hôpital n''est pas guérir. C''est changer de décor, souvent trop tôt, avec une fatigue que l''on sous-estime.

Avant le retour : qui sera là la première nuit ? Le logement est-il praticable ? Faut-il un fauteuil, un lit, une présence diurne ? La famille sur place peut-elle tenir, ou est-elle déjà à bout ?

Akeva Care intervient souvent à ce moment-là : garde de jour, garde de nuit, parfois 24h/24 le temps de stabiliser, et location de matériel si besoin.

Le bon réflexe est d''anticiper la sortie, pas d''attendre la crise du troisième soir.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('la-nuit-moment-le-plus-fragile', 3, 'La nuit, le moment le plus fragile', 'Chutes, désorientation, solitude : pourquoi la garde de nuit change souvent toute l''équation familiale.', '9 juillet 2026', '/images/svc-nuit.jpg', 'Garde de nuit', NULL, 'Le jour, il y a le bruit de la maison, un voisin, un enfant qui passe. La nuit, il n''y a plus que le corps, l''inquiétude et le silence.

Beaucoup de familles tiennent la journée et s''effondrent sur les nuits. Une garde de nuit n''est pas un luxe : c''est parfois la seule manière d''éviter une chute, une errance, ou l''épuisement de l''aidant.

À l''hôpital, c''est encore plus vrai. Les équipes soignantes ont leurs missions. Elles ne peuvent pas tenir la main jusqu''au matin.

Si les nuits sont devenues le sujet dont on ne parle plus autour de la table, parlez-nous-en.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('parler-troubles-psychiques-en-famille', 4, 'Parler des troubles psychiques en famille', 'Sans diagnostic improvisé, sans honte : comment organiser une présence utile autour d''un proche en souffrance.', '18 juin 2026', '/images/svc-psy.jpg', 'Accompagnement', NULL, 'Dans beaucoup de familles, le trouble psychique se dit à mots couverts. On parle de « crise », de « caractère », de « fatigue ». Pendant ce temps, le quotidien se délite.

Un accompagnement à domicile n''est pas un traitement. Il ne remplace ni le médecin ni le psychologue. Il offre autre chose : un cadre, une présence calme, des routines, un relais pour les proches.

Chez Akeva Care, cet accompagnement se fait toujours en complément du suivi des professionnels de santé. Nous n''établissons aucun diagnostic.

Si vous ne savez plus comment tenir la maison autour d''un frère, d''une mère, d''un conjoint, un premier échange confidentiel peut déjà alléger la charge.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('aidants-familiaux-tenir-dans-la-duree', 5, 'Aidants familiaux : tenir dans la durée', 'Aimer ne suffit pas à empêcher l''épuisement. Relais, nuit, diaspora : des appuis concrets.', '2 juin 2026', '/images/hero-home.jpg', 'Familles', '5 min', 'L''aidant familial camerounais — souvent une fille, une belle-fille, une sœur — porte à la fois le soin, la maison, parfois le travail et la honte de « ne plus y arriver ».

Demander une présence professionnelle n''est pas abandonner. C''est refuser que tout repose sur une seule personne jusqu''à la rupture.

Quelques heures en journée, une nuit par semaine, un relais le week-end : l''accompagnement se dose. Il n''est pas tout ou rien.

Akeva Care existe aussi pour cela : que les familles restent des familles, pas des équipes de garde improvisées.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('quand-un-parent-refuse-laide', 6, 'Quand un parent refuse l''aide : par où commencer', 'Fierté, peur de déranger, méfiance : comment ouvrir la conversation sans forcer.', '20 mai 2026', '/images/svc-ages.jpg', 'Familles', NULL, 'Beaucoup de personnes âgées refusent d''abord. Pas par caprice : par dignité. Accepter une présence, c''est admettre que l''on n''est plus tout à fait seul maître de sa maison.

Évitez le mot « garde ». Parlez d''une personne qui vient pour les courses, les repas, la compagnie. Proposez un essai de quelques jours, pas un contrat à vie.

Si vous vivez à l''étranger, ne négociez pas uniquement par téléphone en crise. Un conseiller Akeva Care peut expliquer le cadre, les limites, et rassurer votre parent sans le mettre en accusation.

Le refus n''est pas toujours définitif. Souvent, c''est la première visite — calme, respectueuse — qui débloque ce que dix sermons familiaux n''ont pas obtenu.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('rester-chez-soi-en-vieillissant', 7, 'Vieillir chez soi à Yaoundé ou Douala : ce qu''il faut organiser', 'Le domicile reste le lieu le plus désiré. Encore faut-il le rendre tenable.', '8 mai 2026', '/images/svc-24h.jpg', 'Personnes âgées', NULL, 'Rester chez soi n''est pas un slogan. C''est une organisation : repas, déplacements dans le logement, nuit, médicaments prescrits à rappeler, visites, solitude.

Commencez par trois questions : votre proche peut-il se lever seul ? Mange-t-il réellement ? Qui est là après 20 heures ?

Ensuite seulement viennent les formules : quelques heures, une journée, une nuit, une présence 24h/24. On ajuste. On n''impose pas un dispositif trop lourd dès le premier jour.

Akeva Care construit cette présence à Yaoundé et Douala, en complément du suivi médical — jamais à sa place.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('famille-a-lhopital-ce-que-lon-peut-deleguer', 8, 'À l''hôpital : ce que la famille peut déléguer', 'Rester au chevet 24 heures n''est pas toujours possible. Voici ce qu''une présence organisée prend vraiment en charge.', '24 avril 2026', '/images/svc-hopital.jpg', 'Après l''hôpital', NULL, 'Dans les hôpitaux de Yaoundé et Douala, la famille est souvent le relais invisible : eau, repas, nuit, information. Quand personne ne peut rester, le patient se retrouve seul entre deux visites du personnel soignant.

Une présence Akeva Care n''est pas un soignant de l''établissement. Elle tient compagnie, aide aux gestes simples autorisés, et tient la famille informée.

C''est particulièrement utile la nuit, le week-end, ou lorsque les enfants vivent à l''étranger.

Dites-nous l''établissement, les horaires, et ce que vous attendez exactement. Nous organisons dans le respect du règlement de l''hôpital.');
INSERT INTO articles (slug, order_index, title, excerpt, date_label, image, category, read_time, content) VALUES ('materiel-pour-securiser-le-domicile', 9, 'Sécuriser le domicile : le matériel qui change vraiment la vie', 'Fauteuil, déambulateur, lit : comment choisir sans encombrer la maison.', '11 avril 2026', '/images/svc-materiel.jpg', 'Après l''hôpital', NULL, 'Après une hospitalisation, on veut tout acheter. Ce n''est pas toujours utile. Un déambulateur mal choisi encombre. Un lit trop tôt humilie. Un fauteuil trop tard expose à la chute.

La bonne question : de quoi votre proche a-t-il besoin cette semaine, pas « un jour » ?

Akeva Care conseille et loue selon disponibilités à Yaoundé et Douala. Le matériel prend tout son sens avec une présence formée à l''utiliser dans le quotidien.

Demandez-nous ce dont vous avez réellement besoin. Nous vous dirons ce qui est en stock — sans vous vendre le catalogue entier.');

DELETE FROM testimonials;
INSERT INTO testimonials (order_index, quote, name, role) VALUES (0, 'Je vis à Paris. Savoir que quelqu''un est auprès de ma mère à Yaoundé, et m''écrire le soir, a changé mes nuits.', 'A. M.', 'Fille — diaspora, France');
INSERT INTO testimonials (order_index, quote, name, role) VALUES (1, 'Ce n''est pas « une garde ». C''est une organisation. On savait qui venait, ce qui était fait, et qui appeler.', 'S. N.', 'Fils — Douala');
INSERT INTO testimonials (order_index, quote, name, role) VALUES (2, 'Après l''hôpital, les trois premières nuits à la maison nous faisaient peur. Ils ont tenu le relais. Nous avons pu respirer.', 'C. E.', 'Famille — Yaoundé');

DELETE FROM services;
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('garde-malade', 0, 'Garde malade', 'Garde malade', 'Une présence attentive à domicile ou à l''hôpital, de jour, de nuit ou en continu.', 'Garde malade à domicile et à l''hôpital', 'Lorsqu''un proche est malade, dépendant ou hospitalisé, la présence compte autant que l''organisation. Akeva Care assure une garde malade professionnelle, humaine et encadrée — à domicile comme à l''hôpital.', '/images/svc-hopital.jpg', 'Demander une garde malade', 'Bonjour Akeva Care, je souhaite demander une garde malade pour un proche.', '[{"title":"Garde de jour","text":"Une présence adaptée aux besoins du quotidien, de la toilette d''accompagnement aux repas et à la surveillance."},{"title":"Garde de nuit","text":"Une veille rassurante lorsque la nuit devient le moment le plus fragile pour votre proche — et pour vous."},{"title":"Garde 24h/24","text":"Une organisation continue, avec relais, pour les situations qui demandent une présence permanente."},{"title":"Accompagnement hospitalier","text":"Quelqu''un à ses côtés quand la famille ne peut pas rester en permanence à l''hôpital."}]', '["Aide dans les activités quotidiennes relevant du service","Présence et surveillance selon les limites professionnelles d''Akeva Care","Transmission d''informations à la famille selon nos procédures","Organisation à domicile ou à l''hôpital, à Yaoundé et Douala","Coordination avec la famille, y compris à distance"]', '["Akeva Care n''est pas un établissement de santé et ne remplace pas un médecin, un infirmier ou un traitement prescrit.","Les actes médicaux restent du ressort des professionnels de santé habilités."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('auxiliaire-de-vie', 1, 'Auxiliaire de vie', NULL, 'Un soutien concret pour préserver le confort, l''autonomie et la dignité au quotidien.', 'Auxiliaire de vie à domicile', 'L''auxiliaire de vie Akeva Care aide votre proche dans les gestes du quotidien : se lever, s''habiller, se nourrir, se déplacer, tenir la maison. Une présence utile, respectueuse, jamais intrusive.', '/images/svc-auxiliaire.jpg', 'Demander une auxiliaire de vie', 'Bonjour Akeva Care, je souhaite une auxiliaire de vie à domicile.', '[{"title":"Aide à la toilette et à l''habillage","text":"Un accompagnement discret pour les soins d''hygiène relevant du service, dans le respect de l''intimité."},{"title":"Repas et hydratation","text":"Préparation, aide à la prise des repas et vigilance sur l''hydratation, selon les habitudes de votre proche."},{"title":"Entretien léger du cadre de vie","text":"Un environnement propre, rangé et rassurant, sans se substituer à un service de ménage complet."},{"title":"Compagnie et stimulation","text":"Conversation, promenade, lecture, présence humaine — pour que la journée ne soit pas seulement « surveillée »."}]', '["Aide aux actes essentiels de la vie quotidienne","Présence adaptée au rythme de la personne","Compte-rendu simple à la famille","Intervention à domicile à Yaoundé et Douala"]', '["L''auxiliaire de vie n''effectue pas d''actes médicaux.","Le service s''inscrit en complément du suivi médical existant."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('accompagnement-hospitalier', 2, 'Accompagnement hospitalier', NULL, 'Une présence humaine à l''hôpital, lorsque la famille ne peut pas rester en permanence.', 'Accompagnement hospitalier à Yaoundé et Douala', 'Un séjour à l''hôpital isole. Akeva Care assure une présence auprès du patient : compagnie, vigilance, lien avec la famille, aide dans les gestes simples autorisés. Pour que personne ne reste seul entre deux visites.', '/images/svc-hopital.jpg', 'Demander un accompagnement hospitalier', 'Bonjour Akeva Care, j''ai besoin d''un accompagnement hospitalier.', '[{"title":"Présence au chevet","text":"Une personne dédiée reste auprès de votre proche pendant les créneaux convenus, jour ou nuit."},{"title":"Lien avec la famille","text":"Vous êtes informés selon nos procédures : ce qui s''est passé, l''état apparent, les besoins observés."},{"title":"Aide aux gestes simples","text":"Confort, hydratation, installation, compagnie — dans le respect du règlement de l''établissement."},{"title":"Relais pour la diaspora","text":"Si vous vivez à l''étranger, nous organisons la présence et le suivi à votre place."}]', '["Garde hospitalière de jour, de nuit ou en relais","Coordination avec la famille","Respect des consignes de l''établissement de santé"]', '["Nous ne remplaçons pas le personnel soignant de l''hôpital.","Nous n''intervenons pas dans les actes médicaux ni dans les décisions cliniques."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('garde-de-jour', 3, 'Garde de jour', NULL, 'Une présence adaptée aux besoins quotidiens de votre proche, pendant la journée.', 'Garde de jour à domicile', 'La journée est faite de repas, de déplacements, de solitude parfois. La garde de jour Akeva Care installe une présence utile : aide, surveillance, compagnie, et un rythme qui rassure toute la famille.', '/images/svc-jour.jpg', 'Demander une garde de jour', 'Bonjour Akeva Care, je souhaite une garde de jour.', '[{"title":"Créneaux souples","text":"Quelques heures ou la journée complète, selon la situation et le rythme de votre proche."},{"title":"Aide quotidienne","text":"Repas, déplacements dans le logement, hygiène relevant du service, stimulation, courses légères."},{"title":"Pour les aidants","text":"Un relais pour travailler, se reposer ou simplement souffler — sans culpabilité."},{"title":"Suivi familial","text":"Un point régulier pour que vous sachiez comment s''est passée la journée."}]', '["Présence diurne à domicile","Aide aux activités quotidiennes relevant du service","Transmission d''informations à la famille"]', '["La garde de jour n''est pas un service médical d''urgence."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('garde-de-nuit', 4, 'Garde de nuit', NULL, 'Une veille rassurante lorsque la nuit devient le moment le plus fragile.', 'Garde de nuit à domicile et à l''hôpital', 'La nuit, les chutes, la désorientation, l''angoisse ou la douleur prennent une autre ampleur. Akeva Care organise une garde de nuit : présence, vigilance, appel de la famille si besoin.', '/images/svc-nuit.jpg', 'Demander une garde de nuit', 'Bonjour Akeva Care, je souhaite une garde de nuit.', '[{"title":"Veille attentive","text":"Une présence dans le logement ou à l''hôpital, prête à intervenir dans le cadre de sa mission."},{"title":"Réassurance","text":"Votre proche n''est pas seul. Vous pouvez dormir — ou travailler à l''étranger — plus sereinement."},{"title":"Situations fréquentes","text":"Retour d''hospitalisation, personne âgée fragile, maladie, troubles du comportement nocturne."},{"title":"Relais le matin","text":"Transmission claire à la famille ou à l''équipe de jour."}]', '["Présence nocturne organisée","Surveillance selon les limites professionnelles","Alerte de la famille selon nos procédures"]', '["La garde de nuit n''est pas un service d''urgence médicale.","En cas de détresse vitale, les secours compétents sont contactés."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('accompagnement-24h', 5, 'Accompagnement 24h/24', NULL, 'Une organisation continue, avec relais, pour les besoins de présence permanente.', 'Accompagnement 24h/24', 'Certaines situations ne souffrent pas d''interruption : grande dépendance, fin de vie à domicile, post-hospitalisation délicate, troubles sévères. Akeva Care organise une présence 24h/24, avec des relais clairs et un suivi de la famille.', '/images/svc-24h.jpg', 'Demander un accompagnement 24h/24', 'Bonjour Akeva Care, j''ai besoin d''un accompagnement 24h/24.', '[{"title":"Organisation en relais","text":"Des équipes se succèdent pour garantir la continuité, sans épuisement ni trou dans la présence."},{"title":"Plan personnalisé","text":"Horaires, habitudes, points de vigilance et consignes familiales sont formalisés dès le départ."},{"title":"Suivi rapproché","text":"La famille — sur place ou depuis l''étranger — reçoit des points réguliers."},{"title":"Domicile ou hôpital","text":"Le dispositif s''adapte au lieu de vie et peut évoluer si la situation change."}]', '["Présence continue organisée","Coordination des relais","Compte-rendu familial selon nos procédures"]', '["La continuité de présence n''équivaut pas à une hospitalisation à domicile.","Les soins médicaux restent du ressort des professionnels de santé."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('personnes-agees', 6, 'Personnes âgées', NULL, 'Une présence humaine pour préserver confort, autonomie et sécurité.', 'Accompagnement des personnes âgées', 'Vieillir chez soi est souvent le souhait le plus profond. Akeva Care accompagne les personnes âgées à Yaoundé et Douala avec douceur, respect et organisation — pour que le domicile reste un lieu de vie, pas un lieu d''abandon.', '/images/svc-ages.jpg', 'Parler de mon parent', 'Bonjour Akeva Care, je souhaite un accompagnement pour une personne âgée.', '[{"title":"Préserver l''autonomie","text":"Nous aidons sans se substituer : chaque geste que la personne peut encore faire est respecté."},{"title":"Sécurité au quotidien","text":"Présence, vigilance sur les déplacements, les repas, l''hydratation et les signes d''alerte simples."},{"title":"Compagnie véritable","text":"Parler, écouter, marcher, prier, regarder un match : la relation humaine n''est pas un extra."},{"title":"Soutien aux familles","text":"Un relais clair pour les enfants, y compris ceux qui vivent à l''étranger."}]', '["Accompagnement à domicile adapté à l''âge et à la situation","Aide quotidienne et présence humaine","Lien organisé avec la famille"]', '["Nous ne remplaçons pas un suivi gériatrique médical."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('accompagnement-troubles-psychiques', 7, 'Accompagnement spécialisé des troubles psychiques', NULL, 'Un accompagnement quotidien adapté, en complément du suivi des professionnels de santé.', 'Accompagnement spécialisé des troubles psychiques', 'Vivre avec un trouble psychique — ou accompagner un proche qui en souffre — demande constance, calme et cadre. Akeva Care propose une présence quotidienne adaptée, toujours en complément du suivi médical et psychologique existant.', '/images/svc-psy.jpg', 'Parler à un conseiller', 'Bonjour Akeva Care, je souhaite un accompagnement pour un proche concerné par des troubles psychiques.', '[{"title":"Présence apaisante","text":"Un cadre stable, une voix calme, des routines qui rassurent — sans jamais forcer."},{"title":"Complément du soin","text":"Nous ne soignons pas. Nous accompagnons le quotidien, aux côtés des professionnels de santé."},{"title":"Soutien à la famille","text":"Un relais pour les proches épuisés, et un lien clair pour la diaspora."},{"title":"Discrétion","text":"La dignité de la personne et la confidentialité de la situation sont non négociables."}]', '["Présence quotidienne adaptée","Aide aux routines et à l''organisation du jour","Transmission d''observations à la famille selon nos procédures"]', '["Akeva Care n''est pas un service de psychiatrie et n''établit aucun diagnostic.","L''accompagnement se fait uniquement en complément du suivi des professionnels de santé.","Nous n''intervenons pas dans les situations de crise psychiatrique aiguë : les services compétents doivent être contactés."]');
INSERT INTO services (slug, order_index, title, menu_title, short, h1, intro, image, cta, whatsapp_message, highlights, included, limits) VALUES ('location-materiel-medical', 8, 'Location de matériel médical', NULL, 'Le bon équipement, au bon moment, pour sécuriser le domicile ou le retour d''hôpital.', 'Location de matériel médical', 'Un lit médicalisé, un fauteuil, un déambulateur peuvent changer un retour à domicile. Akeva Care facilite la location de matériel médical pour accompagner l''autonomie et la sécurité — en complément de nos présences humaines.', '/images/svc-materiel.jpg', 'Demander du matériel', 'Bonjour Akeva Care, je souhaite des informations sur la location de matériel médical.', '[{"title":"Équipements courants","text":"Fauteuil roulant, déambulateur, canne, lit médicalisé, matelas anti-escarres, chaise percée — selon disponibilités."},{"title":"Conseil d''usage","text":"Nous vous aidons à identifier ce qui est réellement utile, sans surcharger le domicile."},{"title":"Couplé à l''accompagnement","text":"Le matériel prend tout son sens avec une présence formée à l''utiliser dans le quotidien."},{"title":"Yaoundé et Douala","text":"Demandez-nous la disponibilité pour votre ville : nous organisons selon le stock."}]', '["Conseil sur le matériel adapté à la situation","Location selon disponibilités à Yaoundé et Douala","Possibilité de combiner matériel et présence humaine"]', '["La location dépend des stocks et des délais.","Akeva Care ne vend pas de dispositifs implantables et n''effectue pas d''installation hospitalière complexe."]');
